---
- name: Setup vagrant
  hosts: all
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - curl
          - wget
          - nano
          - htop
          - nginx
        state: latest
        update_cache: true